# Generated by Django 4.2.8 on 2024-03-15 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifymodel',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='notifymodel',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='notifymodel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifymodel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blocked'), (1, 'Favorites'), (2, 'Teased'), (3, 'Upvoted'), (4, 'Downvoted'), (5, 'Visited'), (6, 'Message')]),
        ),
    ]
