# Generated by Django 4.2.8 on 2024-03-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifapi', '0002_remove_notifymodel_receiver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
