# Generated by Django 4.2.8 on 2024-04-20 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifapi', '0003_notifymodel_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymodel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='redirect_url',
            field=models.CharField(default='/', max_length=120),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifymodel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blocked'), (1, 'Favorites'), (2, 'Teased'), (3, 'Upvoted'), (4, 'Downvoted'), (5, 'Visited'), (6, 'Message')], default=5),
        ),
    ]
